-- 1. Liste o cpf e o nome dos espectadores que seguem mais de 1 pessoa (HAVING, GROUP BY, INNER JOIN)
SELECT S.CPF_SEGUIDOR, E.NOME, COUNT(*) as NUM_SEGUIDOS 
FROM SEGUE S
INNER JOIN ESPECTADOR E
ON S.CPF_SEGUIDOR = E.CPF
GROUP BY S.CPF_SEGUIDOR, E.NOME
HAVING COUNT(*) > 1;

-- 2. Encontre os streamers que não possuem canais
SELECT * FROM STREAMER 
WHERE CPF NOT IN (SELECT CPF FROM CANAL);

-- 3. Encontre o conteúdo com maior duração em cada canal (SUBSELECT, GROUP BY, INNER JOIN)
SELECT C.NOME_CANAL, CT.TITULO, CT.DURACAO
FROM CONTEUDO CT
INNER JOIN CANAL C 
ON CT.CPF_STREAMER = C.CPF AND CT.NOME_CANAL = C.NOME_CANAL
WHERE (CT.CPF_STREAMER, CT.NOME_CANAL, CT.DURACAO) IN (
    SELECT CPF_STREAMER, NOME_CANAL, MAX(DURACAO)
    FROM CONTEUDO
    GROUP BY CPF_STREAMER, NOME_CANAL
);

-- 4. Projete O nome e o CPF dos espectadores que não assinam nenhum canal (LEFT OUTER JOIN)
SELECT E.CPF, E.NOME
FROM ESPECTADOR E LEFT OUTER JOIN ASSINA A ON E.CPF = A.CPF_ESP
WHERE A.CPF_STR IS NULL
