-- CRIA TABELA USUÁRIO
CREATE TABLE USUARIO(
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(80) CONSTRAINT NN_USUARIO_NOME NOT NULL,
    END_CEP VARCHAR(8)
    END_COMPLEMENTO VARCHAR(255)
);

-- CRIA TABELA E-MAIL
CREATE TABLE EMAIL(
    CPF VARCHAR(11),
    EMAIL VARCHAR(255),
    CONSTRAINT PK_EMAIL PRIMARY KEY (CPF, EMAIL) 
    CONSTRAINT FK_EMAIL FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
)

-- CRIA TABELA ESPECTADOR

CREATE TABLE ESPECTADOR(
    CPF VARCHAR(11) PRIMARY KEY,
    CONSTRAINT FK_ESPECTADOR FOREIGN KEY (CPF) REFERENCES USUARIO (CPF)
)

-- CRIA TABELA STREAMER

CREATE TABLE STREAMER(
    CPF VARCHAR(11) PRIMARY KEY,
    CONSTRAINT FK_STREAMER FOREIGN KEY (CPF) REFERENCES USUARIO (CPF)
)

-- CRIA TABELA CATEGORIA INTERESSE
CREATE TABLE CATEGORIA_INTERESSE(
    CPF VARCHAR(11),
    EMAIL VARCHAR(255),
    CONSTRAINT PK_CATEGORIA_INTERESSE PRIMARY KEY (CPF, EMAIL)
    CONSTRAINT FK_CATEGORIA_INTERESSE FOREIGN KEY (CPF) REFERENCES ESPECTADOR(CPF)
)

-- CRIA TABELA SEGUE
CREATE TABLE SEGUE(
    CPF_SEGUIDOR VARCHAR(11),
    CPF_SEGUIDO VARCHAR(11),
    CONSTRAINT PK_SEGUE PRIMARY KEY (CPF_SEGUIDOR, CPF_SEGUIDO)
    CONSTRAINT FK_CPF_SEGUIDOR FOREIGN KEY (CPF_SEGUIDOR) REFERENCES ESPECTADOR(CPF)
    CONSTRAINT FK_CPF_SEGUIDO FOREIGN KEY (CPF_SEGUIDO) REFERENCES ESPECTADOR(CPF)
)

-- CRIA TABELA CANAL
CREATE TABLE CANAL(
    CPF VARCHAR(11),
    NOME_CANAL VARCHAR(255),
    DESCRICAO VARCHAR(255),
    CONSTRAINT PK_CANAL PRIMARY KEY (CPF, NOME_CANAL)
    CONSTRAINT FK_CANAL FOREIGN KEY (CPF) REFERENCES STREAMER(CPF)
)

-- CRIA TABELA CATEGORIA
CREATE TABLE CATEGORIA(
    CPF VARCHAR(11),
    NOME_CANAL VARCHAR(255),
    CATEGORIA VARCHAR(20),
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (CPF, NOME_CANAL, CATEGORIA)
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (CPF, NOME_CANAL) REFERENCES CANAL(CPF, NOME_CANAL)
)

--CRIA TABELA CONTEÚDO
CREATE TABLE CONTEUDO(
    ID NUMBER(8) PRIMARY KEY
    TITULO VARCHAR(255),
    DESCRICAO VARCHAR(255),
    DURACAO NUMBER,
    CPF_STREAMER VARCHAR(11) NOT NULL,
    NOME_CANAL VARCHAR(255) NOT NULL,
    CONSTRAINT FK_CONTEUDO FOREIGN KEY (CPF_STREAMER, NOME_CANAL) REFERENCES STREAMER(CPF, NOME_CANAL)
)

--CRIA TABELA VISUALIZA
CREATE TABLE VISUALIZA(
    CPF VARCHAR(11),
    ID NUMBER(8),
    CONSTRAINT PK_VISUALIZA PRIMARY KEY (CPF, ID)
    CONSTRAINT FK_VISUALIZA_CPF FOREIGN KEY (CPF) REFERENCES ESPECTADOR(CPF)
    CONSTRAINT FK_VISUALIZA_ID FOREING KEY (ID) REFERENCES CONTEUDO (ID)
)